### ISSUE TITLE
Over-eager warning about wasted charge

### ISSUE THREAD

**Issue by RobertBolender** [boardgamers/gaia-project#108]
I was just given the opportunity to charge my last 3 power tokens from area 2 to area 3, and received a warning that I would have 2 "wasted" charge during the income phase. (1 pt income, 4 charge income)

However, I hadn't passed yet, so would have plenty of opportunity to spend that charge first! Should this warning only be happening if I've already passed, or if we can somehow detect that I'm *close* to passing?

**Comment by coyotte508** [comment]
It should only trigger when you've passed
