### ISSUE TITLE
Players should auto-decline power charging after passing in the final round

### ISSUE THREAD

**Issue by RobertBolender** [boardgamers/gaia-project#119]
I can't think of any valid reason for a player to charge power after passing in the final round, so this would help speed things up.

**Comment by coyotte508** [comment]
It used to be like that (except for free power), maybe the autocharge settings changed that

**Comment by zeitlinger** [comment]
What game did this happen?

**Comment by RobertBolender** [comment]
`4-knowledge-4-coins`, user was Mathguy playing as Terrans
