### ISSUE TITLE
Warning when declining "up research" after getting a tech

### ISSUE THREAD

**Issue by coyotte508** [boardgamers/gaia-project#140]
https://forum.boardgamers.space/topic/202/suggestion-alert-when-declining-tech-advance

**Comment by zeitlinger** [comment]
Is there a reason a allow the decline at all?

**Comment by coyotte508** [comment]
I guess if next round there is a `a >> 2vp` and you have very few remaining advances.

**Comment by coyotte508** [comment]
A more concrete example is if the up research would take you to the last level of a specific track. You may want to save your green federation.
