### ISSUE TITLE
Warning when using the range booster "range booster not yet used"

### ISSUE THREAD

**Issue by RobertBolender** [boardgamers/gaia-project#141]
![image](https://user-images.githubusercontent.com/3677807/120738180-41a5d600-c4a4-11eb-897d-919ba61cfe56.png)

**Comment by zeitlinger** [comment]
@RobertBolender  IIUC, this is an incorrect warning - can you provide a link to the game?

**Comment by RobertBolender** [comment]
> @RobertBolender IIUC, this is an incorrect warning - can you provide a link to the game?

https://www.boardgamers.space/game/Yeeting-skyscraper-1175
User: CountRobert
Turn: 3.4

I don't specifically remember whether the popup was displayed, but the "Build Mine" button was definitely yellow/orange and had the warning text on hover after I activated the range special.

**Comment by zeitlinger** [comment]
Just reproduced it

![image](https://user-images.githubusercontent.com/2832627/120835031-197dac00-c564-11eb-8440-36c782b0716c.png)

it warns you that building a mine without a booster would probably not make sense.

Did you see something different - or do you see a way to improve the behavior?

**Comment by RobertBolender** [comment]
I sure thought that second "Build a Mine" button was yellow when I clicked it, but it could be a trick of my imagination. I'll pay more attention next time I get a range booster and will re-open the issue if I can confirm it again.
