### ISSUE TITLE
Ambas not being able to take their PI action

### ISSUE THREAD

**Issue by coyotte508** [boardgamers/gaia-project#226]
https://www.boardgamers.space/game/Imaginary-torpedo-2098

After selecting the PI action (before selecting the mine to swap), they have an error in the UI, freezing them 

![image](https://user-images.githubusercontent.com/342922/143832207-812a4c12-2761-4b8b-b198-1bbcd9efcc10.png)

**Comment by zeitlinger** [comment]
@coyotte508 you can tell the user that the fix is deployed

**Comment by coyotte508** [comment]
Thanks!!
