### ISSUE TITLE
Itars variant in 2p visual inconsistency

### ISSUE THREAD

**Issue by condekind** [boardgamers/gaia-project#87]
Itars still show the +1t income in their board (out of the PI slot). I'll check if it shows +1t in their PI slot after built soon, but it's probably still using their regular values.

It's just a visual inconsistency, since the actual income is correct (I didn't get +1t in the first round)

Tested in match: https://www.boardgamers.space/game/Piramidal-tatu-8014

**Comment by coyotte508** [comment]
I think it *may* have been fixed by https://github.com/boardgamers/gaia-project/commit/19364e42d8ecd9a017a2e3dfeb43cc9701cae4f3
